"""add lead threads

Revision ID: 0540016ba120
Revises: f592126550b7
Create Date: 2024-09-05 21:35:29.308722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0540016ba120'
down_revision: Union[str, None] = 'f592126550b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_thread',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('array_comments', sa.Text(), nullable=True),
    sa.Column('array_attachments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.drop_table('lead_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('seq', sa.INTEGER(), nullable=False),
    sa.Column('posted_by', sa.VARCHAR(), nullable=False),
    sa.Column('posted_at', sa.DATE(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=False),
    sa.Column('attachment_path', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lead_thread')
    # ### end Alembic commands ###
