"""add fixed assets

Revision ID: 100505fe4a58
Revises: 977f254578a9
Create Date: 2025-05-04 15:17:01.969535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100505fe4a58'
down_revision: Union[str, None] = '977f254578a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('launched_at', sa.Date(), nullable=False),
    sa.Column('obtained_at', sa.Date(), nullable=False),
    sa.Column('obtained_type', sa.String(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('structure_or_use', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('depreciating_years', sa.Integer(), nullable=True),
    sa.Column('depreciation_expense_total_at_last_fiscal_year', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_assets')
    # ### end Alembic commands ###
