"""add items, projects

Revision ID: 2a879835c189
Revises: b6d23dcbd2f0
Create Date: 2024-07-23 23:05:07.150292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a879835c189'
down_revision: Union[str, None] = 'b6d23dcbd2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('display_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_code', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('loanched_at', sa.Date(), nullable=False),
    sa.Column('partner', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('quotation_issued_at', sa.Date(), nullable=True),
    sa.Column('quotation_no', sa.String(), nullable=True),
    sa.Column('contracted_at', sa.Date(), nullable=True),
    sa.Column('contracted_no', sa.String(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('canceled_at', sa.Date(), nullable=True),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('quotation_amount', sa.Integer(), nullable=True),
    sa.Column('quotation_cost', sa.Integer(), nullable=True),
    sa.Column('quotation_profit', sa.Integer(), nullable=True),
    sa.Column('contract_amount', sa.String(), nullable=True),
    sa.Column('contract_cost', sa.Integer(), nullable=True),
    sa.Column('contract_profit', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Double(), nullable=True),
    sa.Column('tax', sa.Integer(), nullable=True),
    sa.Column('completion_conditions', sa.String(), nullable=True),
    sa.Column('reason_for_cancellation', sa.String(), nullable=True),
    sa.Column('number_of_payments', sa.Integer(), nullable=True),
    sa.Column('number_of_deposits', sa.Integer(), nullable=True),
    sa.Column('ammount_of_payments', sa.Integer(), nullable=True),
    sa.Column('amount_of_deposits', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('items')
    # ### end Alembic commands ###
