"""recreate emissions

Revision ID: 4b9e9f41d3ad
Revises: 4c013f263f37
Create Date: 2024-09-08 01:13:41.026800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9e9f41d3ad'
down_revision: Union[str, None] = '4c013f263f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emissions',
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Double(), nullable=False),
    sa.Column('formula', sa.String(), nullable=False),
    sa.Column('emission', sa.Double(), nullable=False),
    sa.Column('aggregation_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('journal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emissions')
    # ### end Alembic commands ###
