"""drop emissions

Revision ID: 4c013f263f37
Revises: e8f80e63a34a
Create Date: 2024-09-08 01:10:36.073118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c013f263f37'
down_revision: Union[str, None] = 'e8f80e63a34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('journal_id', sa.INTEGER(), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=False),
    sa.Column('formula', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('activity', sa.DOUBLE(), nullable=False),
    sa.Column('emission', sa.DOUBLE(), nullable=False),
    sa.Column('aggregation_key', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
