"""drop project_id

Revision ID: 5793230ecb06
Revises: dae4813b7d44
Create Date: 2024-10-16 23:56:37.578858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5793230ecb06'
down_revision: Union[str, None] = 'dae4813b7d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('project_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
