"""add projects

Revision ID: 6f516b94fc6d
Revises: e74e4c790f88
Create Date: 2024-08-14 12:25:16.204527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f516b94fc6d'
down_revision: Union[str, None] = 'e74e4c790f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('launched_at', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.Date(), nullable=False),
    sa.Column('partner', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('estimate_sales', sa.Integer(), nullable=True),
    sa.Column('estimate_cost', sa.Integer(), nullable=True),
    sa.Column('estimate_profit', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Double(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
