"""add leads and activities

Revision ID: 8eb3c1c3722f
Revises: 2a879835c189
Create Date: 2024-08-11 11:22:53.212076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb3c1c3722f'
down_revision: Union[str, None] = '2a879835c189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('postal_no', sa.String(), nullable=False),
    sa.Column('prefecture', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('trade_status', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('first_contacted_at', sa.Date(), nullable=True),
    sa.Column('first_contacted_media', sa.String(), nullable=True),
    sa.Column('last_contacted_at', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('partner_name', sa.String(), nullable=True),
    sa.Column('partner_role', sa.String(), nullable=True),
    sa.Column('partner_tel_1', sa.String(), nullable=True),
    sa.Column('partner_tel_2', sa.String(), nullable=True),
    sa.Column('partner_mail_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emission_source', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('emission_factor', sa.Double(), nullable=False),
    sa.Column('scope_category', sa.String(), nullable=False),
    sa.Column('basis_of_emission_factor', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('leads')
    # ### end Alembic commands ###
