"""initial setup

Revision ID: b6d23dcbd2f0
Revises: 
Create Date: 2024-07-10 12:14:00.114044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d23dcbd2f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entried_at', sa.Date(), nullable=False),
    sa.Column('credit', sa.String(), nullable=False),
    sa.Column('debit', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Double(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=False),
    sa.Column('partner', sa.String(), nullable=False),
    sa.Column('cash_in', sa.Integer(), nullable=False),
    sa.Column('cash_out', sa.Integer(), nullable=False),
    sa.Column('tax_in', sa.Integer(), nullable=False),
    sa.Column('tax_out', sa.Integer(), nullable=False),
    sa.Column('cost_type', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=False),
    sa.Column('fiscal_term', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journals')
    # ### end Alembic commands ###
