"""modify emissions

Revision ID: bfe5c83fd654
Revises: 6f516b94fc6d
Create Date: 2024-08-15 19:25:35.495677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe5c83fd654'
down_revision: Union[str, None] = '6f516b94fc6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emissions', sa.Column('activity', sa.Double(), nullable=False))
    op.add_column('emissions', sa.Column('emission', sa.Double(), nullable=False))
    op.add_column('emissions', sa.Column('aggregation_key', sa.String(), nullable=False))
    op.drop_column('emissions', 'emission_factor')
    op.drop_column('emissions', 'emissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emissions', sa.Column('emissions', sa.DOUBLE(), nullable=False))
    op.add_column('emissions', sa.Column('emission_factor', sa.DOUBLE(), nullable=False))
    op.drop_column('emissions', 'aggregation_key')
    op.drop_column('emissions', 'emission')
    op.drop_column('emissions', 'activity')
    # ### end Alembic commands ###
