"""mod lead threads

Revision ID: e8f80e63a34a
Revises: 0540016ba120
Create Date: 2024-09-05 21:39:35.529333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f80e63a34a'
down_revision: Union[str, None] = '0540016ba120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_threads',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('array_comments', sa.Text(), nullable=True),
    sa.Column('array_attachments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.drop_table('lead_thread')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_thread',
    sa.Column('lead_id', sa.INTEGER(), nullable=False),
    sa.Column('array_comments', sa.TEXT(), nullable=True),
    sa.Column('array_attachments', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.drop_table('lead_threads')
    # ### end Alembic commands ###
