"""add statements

Revision ID: f592126550b7
Revises: 13808a4a89a3
Create Date: 2024-08-24 21:24:21.962161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f592126550b7'
down_revision: Union[str, None] = '13808a4a89a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fiscal_start_date', sa.Date(), nullable=False),
    sa.Column('fiscal_end_date', sa.Date(), nullable=False),
    sa.Column('fiscal_term', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_caption', sa.String(), nullable=False),
    sa.Column('item_category', sa.String(), nullable=False),
    sa.Column('display_seq', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    # ### end Alembic commands ###
